### ISSUE TITLE
TextDraw height  apparently don't work

### ISSUE THREAD

**Issue by digovc** [ikkentim/SampSharp-grandlarc#2]
Hi bro,

I'm trying to make a complex menu with textdraws but I can't understand how manipulate the position and the size of the box in screen.

Can you tell me the reason because the height of the texdraw dont works?
And how can I make this task more easy (complex user interface)?

**Comment by ikkentim** [comment]
I can't remember exactly what sa-mp native you'd have to call in order to change text draw box sizes. All the properties are mapped to these natives. Maybe try changing the LetterSize/LetterHeight or something
